import type { Metadata } from "next";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { NavItems } from "@/public/assets/constants/NavItems";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Miss Universe Sri Lanka 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FloatingNav navItems={NavItems} />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
