// import msworld from "../images/candidates/msworld.png";
// import { StaticImageData } from "next/image";

// export interface Candidate {
//   id: number;
//   name: string;
//   image: string; // Change type to StaticImageData
//   image2: string;
//   // age: number;
//   // from: string;
// }

// export const candidateList: Candidate[] = [
//   {
//     id: 1,
//     name: "Anne Sweetlin",
//     image: "/assets/images/candidates/1-p.png",
//     image2: "/assets/images/candidates_full/1.jpg",
//   },
//   {
//     id: 2,
//     name: "Ayodya Amarasingha",
//     image: "/assets/images/candidates/2-p.png",
//     image2: "/assets/images/candidates_full/2.jpg",
//   },
//   {
//     id: 3,
//     name: "Basma Iqbal",
//     image: "/assets/images/candidates/3-p.png",
//     image2: "/assets/images/candidates_full/3.jpg",
//   },
//   {
//     id: 4,
//     name: "Chamali Perera",
//     image: "/assets/images/candidates/4-p.png",
//     image2: "/assets/images/candidates_full/4.jpg",
//   },
//   {
//     id: 5,
//     name: "Chathurika Hasanthi Kumari Senevirathne",
//     image: "/assets/images/candidates/5-p.png",
//     image2: "/assets/images/candidates_full/5.jpg",
//   },
//   {
//     id: 6,
//     name: "Deepthi Bandara",
//     image: "/assets/images/candidates/6-p.png",
//     image2: "/assets/images/candidates_full/6.jpg",
//   },
//   {
//     id: 7,
//     name: "Dil Samarathunga",
//     image: "/assets/images/candidates/7-p.png",
//     image2: "/assets/images/candidates_full/7.jpg",
//   },
//   {
//     id: 8,
//     name: "Dilhara Sewwandi Abeykoon",
//     image: "/assets/images/candidates/8-p.png",
//     image2: "/assets/images/candidates_full/8.jpg",
//   },
//   {
//     id: 9,
//     name: "Dinuki Thilothma Weragoda",
//     image: "/assets/images/candidates/9-p.png",
//     image2: "/assets/images/candidates_full/9.jpg",
//   },
//   {
//     id: 10,
//     name: "Dr Sanduni Vithanage",
//     image: "/assets/images/candidates/10-p.png",
//     image2: "/assets/images/candidates_full/10.jpg",
//   },
//   {
//     id: 11,
//     name: "Dulakshi Ranaweera",
//     image: "/assets/images/candidates/11-p.png",
//     image2: "/assets/images/candidates_full/11.jpg",
//   },
//   {
//     id: 12,
//     name: "Elizabeth Christina Motha",
//     image: "/assets/images/candidates/12-p.png",
//     image2: "/assets/images/candidates_full/12.jpg",
//   },
//   {
//     id: 13,
//     name: "Fiona David",
//     image: "/assets/images/candidates/13-p.png",
//     image2: "/assets/images/candidates_full/13.jpg",
//   },
//   {
//     id: 14,
//     name: "Hansamali",
//     image: "/assets/images/candidates/14-p.png",
//     image2: "/assets/images/candidates_full/14.jpg",
//   },
//   {
//     id: 15,
//     name: "Haresha Chanchali Silva",
//     image: "/assets/images/candidates/15-p.png",
//     image2: "/assets/images/candidates_full/15.jpg",
//   },
//   {
//     id: 16,
//     name: "Hashini Hewage",
//     image: "/assets/images/candidates/16-p.png",
//     image2: "/assets/images/candidates_full/16.jpg",
//   },
//   {
//     id: 17,
//     name: "Hiruni Wijesinghe",
//     image: "/assets/images/candidates/17-p.png",
//     image2: "/assets/images/candidates_full/17.jpg",
//   },
//   {
//     id: 18,
//     name: "Kalani Athukorala",
//     image: "/assets/images/candidates/18-p.png",
//     image2: "/assets/images/candidates_full/18.jpg",
//   },
//   {
//     id: 19,
//     name: "Kavee Rathnayaka",
//     image: "/assets/images/candidates/19-p.png",
//     image2: "/assets/images/candidates_full/19.jpg",
//   },
//   {
//     id: 20,
//     name: "Kithnija Dayarathne",
//     image: "/assets/images/candidates/20-p.png",
//     image2: "/assets/images/candidates_full/20.jpg",
//   },
//   {
//     id: 21,
//     name: "Lakshika Madumali Rodrigo",
//     image: "/assets/images/candidates/21-p.png",
//     image2: "/assets/images/candidates_full/21.jpg",
//   },
//   {
//     id: 22,
//     name: "Lihasha Lindsay White",
//     image: "/assets/images/candidates/22-p.png",
//     image2: "/assets/images/candidates_full/22.jpg",
//   },
//   {
//     id: 23,
//     name: "Melani Fernando",
//     image: "/assets/images/candidates/23-p.png",
//     image2: "/assets/images/candidates_full/23.jpg",
//   },
//   {
//     id: 24,
//     name: "Nelumi Somarathne",
//     image: "/assets/images/candidates/24-p.png",
//     image2: "/assets/images/candidates_full/24.jpg",
//   },
//   {
//     id: 25,
//     name: "Nimali Ekanayaka",
//     image: "/assets/images/candidates/25-p.png",
//     image2: "/assets/images/candidates_full/25.jpg",
//   },
//   {
//     id: 26,
//     name: "Pavani Indulage",
//     image: "/assets/images/candidates/26-p.png",
//     image2: "/assets/images/candidates_full/26.jpg",
//   },
//   {
//     id: 27,
//     name: "Raveena Divya Rekha",
//     image: "/assets/images/candidates/27-p.png",
//     image2: "/assets/images/candidates_full/27.jpg",
//   },
//   {
//     id: 28,
//     name: "Ruvini Priyadarshani",
//     image: "/assets/images/candidates/28-p.png",
//     image2: "/assets/images/candidates_full/28.jpg",
//   },
//   {
//     id: 29,
//     name: "Sahansa Gunarathna",
//     image: "/assets/images/candidates/29-p.png",
//     image2: "/assets/images/candidates_full/29.jpg",
//   },
//   {
//     id: 30,
//     name: "Sanduni Asanka Hettigoda",
//     image: "/assets/images/candidates/30-p.png",
//     image2: "/assets/images/candidates_full/30.jpg",
//   },
//   {
//     id: 31,
//     name: "Sithara Seedevi Vidana",
//     image: "/assets/images/candidates/31-p.png",
//     image2: "/assets/images/candidates_full/31.jpg",
//   },
//   {
//     id: 32,
//     name: "Sujini Bandara",
//     image: "/assets/images/candidates/32-p.png",
//     image2: "/assets/images/candidates_full/32.jpg",
//   },
//   {
//     id: 33,
//     name: "Taniya Warnakula",
//     image: "/assets/images/candidates/33-p.png",
//     image2: "/assets/images/candidates_full/33.jpg",
//   },
//   {
//     id: 34,
//     name: "Thanuri Gunawardhane",
//     image: "/assets/images/candidates/34-p.png",
//     image2: "/assets/images/candidates_full/34.jpg",
//   },
//   {
//     id: 35,
//     name: "Udumbara Sevwandi",
//     image: "/assets/images/candidates/35-p.png",
//     image2: "/assets/images/candidates_full/35.jpg",
//   },
//   {
//     id: 36,
//     name: "Vishmi Danie",
//     image: "/assets/images/candidates/36-p.png",
//     image2: "/assets/images/candidates_full/36.jpg",
//   },
//   {
//     id: 37,
//     name: "Yasasi Chathurangi",
//     image: "/assets/images/candidates/37-p.png",
//     image2: "/assets/images/candidates_full/37.jpg",
//   },
// ];
// //[
// //   { id: 1, name: "Anne Sweetlin", image: msworld },
// //   { id: 2, name: "Ayodya Amarasingha", image: msworld },
// //   { id: 3, name: "Basma Iqbal", image: msworld },
// //   { id: 4, name: "Chamali Perera", image: msworld },
// //   { id: 5, name: "Chathurika Hasanthi Kumari Senevirathne", image: msworld },
// //   { id: 6, name: "Deepthi Bandara", image: msworld },
// //   { id: 7, name: "Dil Samarathunga", image: msworld },
// //   { id: 8, name: "Dilhara Sewwandi Abeykoon", image: msworld },
// //   { id: 9, name: "Dinuki Thilothma Weragoda", image: msworld },
// //   { id: 10, name: "Dr Sanduni Vithanage", image: msworld },
// //   { id: 11, name: "Dulakshi Ranaweera", image: msworld },
// //   { id: 12, name: "Elizabeth Christina Motha", image: msworld },
// //   { id: 13, name: "Fiona David", image: msworld },
// //   { id: 14, name: "Hansamali", image: msworld },
// //   { id: 15, name: "Haresha Chanchali Silva", image: msworld },
// //   { id: 16, name: "Hashini Hewage", image: msworld },
// //   { id: 17, name: "Hiruni Wijesinghe", image: msworld },
// //   { id: 18, name: "Kalani Athukorala", image: msworld },
// //   { id: 19, name: "Kavee Rathnayaka", image: msworld },
// //   { id: 20, name: "Kithnija Dayarathne", image: msworld },
// //   { id: 21, name: "Lakshika Madumali Rodrigo", image: msworld },
// //   { id: 22, name: "Lihasha Lindsay White", image: msworld },
// //   { id: 23, name: "Melani Fernando", image: msworld },
// //   { id: 24, name: "Nelumi Somarathne", image: msworld },
// //   { id: 25, name: "Nimali Ekanayaka", image: msworld },
// //   { id: 26, name: "Pavani Indulage", image: msworld },
// //   { id: 27, name: "Raveena Divya Rekha", image: msworld },
// //   { id: 28, name: "Ruvini Priyadarshani", image: msworld },
// //   { id: 29, name: "Sahansa Gunarathna", image: msworld },
// //   { id: 30, name: "Sanduni Asanka Hettigoda", image: msworld },
// //   { id: 31, name: "Sithara Seedevi Vidana", image: msworld },
// //   { id: 32, name: "Sujini Bandara", image: msworld },
// //   { id: 33, name: "Taniya Warnakula", image: msworld },
// //   { id: 34, name: "Thanuri Gunawardhane", image: msworld },
// //   { id: 35, name: "Udumbara Sevwandi", image: msworld },
// //   { id: 36, name: "Vishmi Daniel", image: msworld },
// //   { id: 37, name: "Yasasi Chathurangi", image: msworld },
// // ];
